
FROM node:22-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .


FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json ./


RUN npm ci
COPY . .
EXPOSE 8083
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
