FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# -----------------------------------------------------------------------------

FROM docker:24-dind AS runner                     
RUN apk add --no-cache dumb-init nodejs npm        
RUN addgroup -g 1001 nodejs
RUN adduser -S -u 1001 -G nodejs nodejs
WORKDIR /app
COPY --from=builder --chown=nodejs:nodejs /app/dist ./dist
COPY --from=builder --chown=nodejs:nodejs /app/package*.json ./
RUN npm ci --omit=dev


EXPOSE 3003                                       

ENTRYPOINT ["dumb-init", "--"]
CMD ["node", "dist/workers/executionWorker.js"]                    
